name: ollama
services:
    ollama:
        volumes:
            - .:/root/.ollama
        ports:
            - 11434:11434
        container_name: ollama
        image: docker.io/ollama/ollama:latest
volumes:
    ollama:
        external: true
        name: ollama
